# Generated by Django 3.1.7 on 2021-02-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_photo',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails'),
        ),
    ]
