# Generated by Django 3.1.7 on 2021-02-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_photo',
            new_name='Thumbnail',
        ),
    ]
