# Generated by Django 3.1.7 on 2021-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210221_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(default='thumbnails/default.jpg', upload_to='thumbnails'),
        ),
    ]
