# Generated by Django 3.1.7 on 2021-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210221_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails'),
        ),
    ]
